// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"github.com/1996Paul-Wen/helloGoZero/safebox/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {

	InitUserRouteGroup(serverCtx)
	InitGreetRouteGroup(serverCtx)
	InitPWDManageRouteGroup(serverCtx)
	userRouteGroup.RegisterToServer(server)
	greetRouteGroup.RegisterToServer(server)
	pwdManageRouteGroup.RegisterToServer(server)

	// 全局中间件
	server.Use(TraceMiddleware)
	server.Use(LogMiddleware)

}
