// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	managedPasswordFieldNames          = builder.RawFieldNames(&ManagedPassword{})
	managedPasswordRows                = strings.Join(managedPasswordFieldNames, ",")
	managedPasswordRowsExpectAutoSet   = strings.Join(stringx.Remove(managedPasswordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	managedPasswordRowsWithPlaceHolder = strings.Join(stringx.Remove(managedPasswordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	managedPasswordModel interface {
		Insert(ctx context.Context, data *ManagedPassword) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ManagedPassword, error)
		Update(ctx context.Context, data *ManagedPassword) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultManagedPasswordModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ManagedPassword struct {
		Id          uint64    `db:"id"`          // 主键ID
		UserId      uint64    `db:"user_id"`     // 用户ID
		Description string    `db:"description"` // 对于本条账号密码的明文描述，将用于es倒排
		Username    string    `db:"username"`    // 用户名（对称加密后的值）
		Password    string    `db:"password"`    // 密码（对称加密后的值）
		Creator     string    `db:"creator"`     // 创建人
		Updator     string    `db:"updator"`     // 更新人
		CreateTime  time.Time `db:"create_time"` // 创建时间
		UpdateTime  time.Time `db:"update_time"` // 更新时间
	}
)

func newManagedPasswordModel(conn sqlx.SqlConn) *defaultManagedPasswordModel {
	return &defaultManagedPasswordModel{
		conn:  conn,
		table: "`managed_password`",
	}
}

func (m *defaultManagedPasswordModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultManagedPasswordModel) FindOne(ctx context.Context, id uint64) (*ManagedPassword, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", managedPasswordRows, m.table)
	var resp ManagedPassword
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultManagedPasswordModel) Insert(ctx context.Context, data *ManagedPassword) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, managedPasswordRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Description, data.Username, data.Password, data.Creator, data.Updator)
	return ret, err
}

func (m *defaultManagedPasswordModel) Update(ctx context.Context, data *ManagedPassword) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, managedPasswordRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Description, data.Username, data.Password, data.Creator, data.Updator, data.Id)
	return err
}

func (m *defaultManagedPasswordModel) tableName() string {
	return m.table
}
