// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type GeneralResponse struct {
	Code    int
	Msg     string
	Data    any
	TraceID string
}
